### ISSUE TITLE
Move to using Github Actions for CI

### ISSUE THREAD

**Issue by G-Rath** [ackama/lighthouse-matchers#17]
We're wanting to move off Travis, and Github Actions is free for open source repos.

**Comment by joshmcarthur** [comment]
Flagging this as low-priority since Travis is also free for open source repos and is working for this fine.

**Comment by joshmcarthur** [comment]
🙈 cancel that, Travis' .org application is dead, and we can't migrate to .com for _reasons_

**Comment by G-Rath** [comment]
Yeah I wasn't too fussed with Travis for this project, but figured this would be a good investment time opportunity for a developer to get some hands on experience setting up CI (+ on converting Travis to GHA, as thats something we've got to do for a bunch of private projects) which is why I held off doing it myself.

The recent developments (or lack thereof) from Travis means to me this is definitely something we should try to do this year, but doesn't have to be right away - if you're not blocked right now I'll grab someone this month to do it or otherwise do it myself so it's done and dusted
