### ISSUE TITLE
Consider using `semantic-release` + conventional commits to do releases

### ISSUE THREAD

**Issue by G-Rath** [ackama/lighthouse-matchers#23]
I think it would be good if we automated the release process to reduce the risk and overhead around doing releases - especially since we don't do that man releases which makes it easy to forgot the process.

This pairs well with using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) as that will allow us to generate the changelog & version based on the commits.

**Comment by G-Rath** [comment]
@joshmcarthur do you have any thoughts or opinions on this?

**Comment by joshmcarthur** [comment]
> especially since we don't do that man releases which makes it easy to forgot the process.

I think this is the key for me. I'm happy to faciliate it getting done (such as providing access to releasers, etc), but if it's something only happening intermittently, it seems a low-value automation.

**Comment by G-Rath** [comment]
I agree it's not high priority given how rarely we do a release, but i do think it has value since currently we need your time if we want do any releasing 😅

For me this is also a good opportunity to learn how gem publishing & management actually works so I'm happy to do the actual work of setting everything up - I just first wanted to check if you were happy with the commit convention first.
