### ISSUE TITLE
Refactor matcher to be more object oriented 

### ISSUE THREAD

**Issue by joshmcarthur** [ackama/lighthouse-matchers#4]
The matcher is implemented as "minimum viable release". The matcher would be a little nicer if it separated concerns into separate unit tested objects.

**Comment by CaraHill** [comment]
https://github.com/ackama/lighthouse-matchers/pull/7

**Comment by joshmcarthur** [comment]
Resolved by https://github.com/ackama/lighthouse-matchers/commit/90bd9fc8ede44fe7d6ae2270a88687a0ca064a13
